"""initial schema with anomaly tables

Creates all six tables in one revision. Until now ``migrations/versions/`` held
only a ``.gitkeep``, so the documented ``alembic upgrade head`` step created
nothing — a fresh environment came up with an empty database and every query
failed at runtime rather than at setup.

Tables: filings_raw, financial_facts, filing_versions, pipeline_audit,
model_runs, fact_anomalies.

Surrogate primary keys use ``BigInteger().with_variant(Integer, "sqlite")``
(see the comment on ``src.schema.Base``) so ORM-level inserts autoincrement
correctly under both PostgreSQL and the SQLite the test suite runs against.

Revision ID: b17f52f92845
Revises:
Create Date: 2026-08-12 06:12:29.725651

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b17f52f92845'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('filing_type', sa.String(length=10), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=True),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.String(length=25), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filing_versions_cik'), 'filing_versions', ['cik'], unique=False)
    op.create_table('filings_raw',
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('filing_type', sa.String(length=10), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('raw_xbrl', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('accession_number')
    )
    op.create_index(op.f('ix_filings_raw_cik'), 'filings_raw', ['cik'], unique=False)
    op.create_index(op.f('ix_filings_raw_filing_date'), 'filings_raw', ['filing_date'], unique=False)
    op.create_index(op.f('ix_filings_raw_pipeline_run_id'), 'filings_raw', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_filings_raw_ticker'), 'filings_raw', ['ticker'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('model_sha256', sa.String(length=64), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('filings_scored', sa.Integer(), nullable=False),
    sa.Column('anomalies_flagged', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('drift_report', sa.JSON(), nullable=True),
    sa.Column('drift_level', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_model_version'), 'model_runs', ['model_version'], unique=False)
    op.create_index(op.f('ix_model_runs_run_id'), 'model_runs', ['run_id'], unique=False)
    op.create_table('pipeline_audit',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_audit_run_id'), 'pipeline_audit', ['run_id'], unique=False)
    op.create_table('fact_anomalies',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.BigInteger(), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('model_score', sa.Float(), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('triggered_by', sa.String(length=8), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rule_violations', sa.JSON(), nullable=True),
    sa.Column('top_contributors', sa.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['filings_raw.accession_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'accession_number', name='uq_anomaly_run_accession')
    )
    op.create_index(op.f('ix_fact_anomalies_accession_number'), 'fact_anomalies', ['accession_number'], unique=False)
    op.create_index(op.f('ix_fact_anomalies_is_anomaly'), 'fact_anomalies', ['is_anomaly'], unique=False)
    op.create_index(op.f('ix_fact_anomalies_model_run_id'), 'fact_anomalies', ['model_run_id'], unique=False)
    op.create_index(op.f('ix_fact_anomalies_score'), 'fact_anomalies', ['score'], unique=False)
    op.create_table('financial_facts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('fact_name', sa.String(length=256), nullable=False),
    sa.Column('fact_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('segment', sa.String(length=256), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['filings_raw.accession_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_facts_accession_number'), 'financial_facts', ['accession_number'], unique=False)
    op.create_index(op.f('ix_financial_facts_fact_name'), 'financial_facts', ['fact_name'], unique=False)
    op.create_index(op.f('ix_financial_facts_period_end'), 'financial_facts', ['period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_facts_period_end'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_fact_name'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_accession_number'), table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index(op.f('ix_fact_anomalies_score'), table_name='fact_anomalies')
    op.drop_index(op.f('ix_fact_anomalies_model_run_id'), table_name='fact_anomalies')
    op.drop_index(op.f('ix_fact_anomalies_is_anomaly'), table_name='fact_anomalies')
    op.drop_index(op.f('ix_fact_anomalies_accession_number'), table_name='fact_anomalies')
    op.drop_table('fact_anomalies')
    op.drop_index(op.f('ix_pipeline_audit_run_id'), table_name='pipeline_audit')
    op.drop_table('pipeline_audit')
    op.drop_index(op.f('ix_model_runs_run_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_model_version'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_filings_raw_ticker'), table_name='filings_raw')
    op.drop_index(op.f('ix_filings_raw_pipeline_run_id'), table_name='filings_raw')
    op.drop_index(op.f('ix_filings_raw_filing_date'), table_name='filings_raw')
    op.drop_index(op.f('ix_filings_raw_cik'), table_name='filings_raw')
    op.drop_table('filings_raw')
    op.drop_index(op.f('ix_filing_versions_cik'), table_name='filing_versions')
    op.drop_table('filing_versions')
    # ### end Alembic commands ###
